[package]
authors = ["Andreas Reich <r_andreas2@web.de>"]
edition = "2021"
name = "blub"
version = "0.1.0"
resolver = "2"

[dependencies]
bytemuck = "1.14"
cgmath = { version = "0.18", features = ["rand", "serde"] }
enumflags2 = "0.7"
env_logger = "0.11"
futures = "0.3"
image = { version = "0.25", default-features = false, features = ["png", "hdr"] }
lazy_static = "1.5"
log = "0.4"
more-asserts = "0.3"
notify = "6.1"
pollster = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shaderc = "0.8"
strum = "0.26"
strum_macros = "0.26"
tobj = "4"

wgpu = { version = "29", features = ["spirv"] }
wgpu-profiler = "0.27"
winit = "0.30"
egui = "0.34"
egui-wgpu = "0.34"
egui-winit = "0.34"

[profile.dev.package."*"]
opt-level = 3
